### ISSUE TITLE
odd behavior on a sub-flow

### ISSUE THREAD

**Issue by nileio** [drmibell/node-red-contrib-queue-gate#10] opened 2020-03-23 02:48 UTC
please refer to https://github.com/node-red/node-red/issues/2513 .
I finally isolate this problem and somehow when I use the q-gate node on a subflow, the built-in `$parent.` keyword that lets you retrieve the parent node context fails. It is odd and I can't think of why (it might not be q-gate itself but something else !) but in my environments i confirmed that using the node on a subflow and using the `$parent.` keyword will not return a value after a deploy & restart of node-red..
could you please test and confirm this behavior or advise otherwise ?

Thank you!!

**Comment by drmibell** [comment] 2020-03-24 22:09
I think I have reproduced the issue, but so far have no idea what might be causing it. There may be a clue in the fact that I seem to see the same behavior with `node-red-contrib-simple-gate`, which  has a very similar structure.

**Comment by nileio** [comment] 2020-03-24 22:44
@drmibell thanks for looking into this and reproducing the issue. It took me so long to figure that this is the cause of my subflows failing.. I find this issue really weird ! I am curious to know the root cause. For now I had to remove all the nodes and simply use a function node.

**Comment by drmibell** [comment] 2020-03-24 23:46
Further clues:
- In addition to `node-red-contrib-simple-gate`, other contributed nodes seem to cause the same behavior, specifically `node-red-contrib-dsm` and `node-red-contrib-random-event-generator`.
- The common denominator seems to be that these nodes read or write node context when they start up or are deployed.
- Why subflows including these nodes behave properly when first created but fail when NR is restarted is not clear.

I will keep poking at this, but if the answer is buried deep in the internals of NR it may be beyond my grasp. Any help is welcome.

**Comment by nileio** [comment] 2020-03-25 00:17
@drmibell interesting points. its definitely applicable only to custom nodes because i use node context on function nodes and that is working fine after restarts too..
so if you reach at some deeper conclusion , let us know.. I would think someone from the core project team may better shed some light on the internals.. I linked this issue to the issue on node-red so hopefully we can get further input..

**Comment by drmibell** [comment] 2020-03-30 19:23
Based on Nick's comments in the [forum](https://discourse.nodered.org/t/issues-using-parent-from-a-subflow/23231/13?u=drmibell), I would like to close this issue.

**Comment by nileio** [comment] 2020-03-31 07:54
https://github.com/node-red/node-red/commit/84771f5864c355664bb48755d7452d29d513a7ba

**Closed** 2020-03-31 07:53 UTC
